# Generated by Django 3.2.10 on 2022-01-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField()),
                (
                    "tournamentType",
                    models.IntegerField(
                        choices=[
                            (0, "Nonetournamenttype"),
                            (1, "Regional"),
                            (3, "Districtevent"),
                            (4, "Districtchampionship"),
                            (5, "Districtchampionshipwithlevels"),
                            (6, "Districtchampionshipdivision"),
                            (7, "Championshipsubdivision"),
                            (8, "Championshipdivision"),
                            (9, "Championship"),
                            (10, "Offseason"),
                            (11, "Offseasonwithazuresync"),
                            (100, "Scrimmage"),
                            (101, "Leaguemeet"),
                            (102, "Qualifier"),
                            (103, "Leaguetournament"),
                            (104, "Ftcchampionship"),
                            (105, "Other"),
                            (106, "Ftc Firstchampionship"),
                            (107, "Superqualifier"),
                            (109, "Innovationchallenge"),
                            (110, "Ftc Offseason"),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("lat", models.FloatField(null=True)),
                ("long", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("location", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.IntegerField(
                        choices=[
                            ("UK", "Unknown"),
                            ("FRC", "FIRST Robotics Competition"),
                            ("FTC", "FIRST Tech Challenge"),
                            ("FLLC", "FIRST LEGO League Challenge"),
                            ("FLLE", "FIRST LEGO League Explore"),
                            ("FLLD", "FIRST LEGO League Discover"),
                        ],
                        default="UK",
                    ),
                ),
                ("year", models.IntegerField(null=True)),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.IntegerField(
                        choices=[
                            ("UK", "Unknown"),
                            ("FRC", "FIRST Robotics Competition"),
                            ("FTC", "FIRST Tech Challenge"),
                            ("FLLC", "FIRST LEGO League Challenge"),
                            ("FLLE", "FIRST LEGO League Explore"),
                            ("FLLD", "FIRST LEGO League Discover"),
                        ],
                        default="UK",
                    ),
                ),
                ("team_num", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.TextField(max_length=100, null=True)),
                ("fullname", models.TextField()),
                ("website", models.TextField(null=True)),
                ("city", models.TextField(blank=True)),
                ("state", models.TextField(blank=True)),
                ("country", models.TextField(blank=True)),
                ("lat", models.FloatField(null=True)),
                ("long", models.FloatField(null=True)),
                ("leagues", models.ManyToManyField(to="events.League")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.season"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.team"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("team_num", "competition"), name="unique_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("year", "competition"), name="unique_season"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="parentLeague",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.league"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="events.season"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="events.league",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="events.season"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="teams",
            field=models.ManyToManyField(to="events.Team"),
        ),
        migrations.AddConstraint(
            model_name="teamyear",
            constraint=models.UniqueConstraint(
                fields=("team", "season"), name="unique_team_year"
            ),
        ),
    ]
