# Generated by Django 3.2.12 on 2022-03-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220326_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='es02_key',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='individual',
            field=models.TextField(help_text="For individual awards like Dean's List", null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_key',
            field=models.CharField(help_text='Official event key from FIRST', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='regular_event',
            field=models.ForeignKey(help_text='Used for a repeating event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.regularevent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tournamentType',
            field=models.IntegerField(choices=[(0, 'FRC None'), (1, 'FRC Regional'), (3, 'FRC District'), (4, 'FRC DCMP'), (5, 'FRC DCMP With Levels'), (6, 'FRC DCMP Sub Division'), (7, 'FRC Champ Subdivision'), (8, 'FRC Champ Division'), (9, 'FRC Championship'), (10, 'FRC Offseason'), (11, 'FRC Offseason With Azure Sync'), (100, 'FTC Scrimmage'), (101, 'FTC League Meet'), (102, 'FTC Qualifier'), (103, 'FTC League Tournament'), (104, 'FTC (local) Championship'), (105, 'FTC Other'), (106, 'FTC Championship'), (107, 'FTC Super Qualifier'), (109, 'FTC Innovation Challenge'), (110, 'FTC Off Season')]),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='pageType',
            field=models.IntegerField(choices=[(0, 'Custom'), (1, 'Teams'), (2, 'Awards')], default=0),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
