# Generated by Django 3.2.12 on 2022-03-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220326_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='individual',
            field=models.CharField(help_text="For individual awards like Dean's List", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='code',
            field=models.CharField(help_text='Gotten straight from FIRST', max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamyear',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamyear',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamyear',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teamyear',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamyear',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
