# Generated by Django 3.2.12 on 2022-03-31 02:23

import aldryn_apphooks_config.fields
import app_data.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20220330_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
            ],
            options={
                'verbose_name': 'Regular Event Config',
            },
        ),
        migrations.CreateModel(
            name='TeamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('competition', models.IntegerField(choices=[('UK', 'Unknown'), ('FRC', 'FIRST Robotics Competition'), ('FTC', 'FIRST Tech Challenge'), ('FLLC', 'FIRST LEGO League Challenge'), ('FLLE', 'FIRST LEGO League Explore'), ('FLLD', 'FIRST LEGO League Discover')])),
            ],
            options={
                'verbose_name': 'Team Listing Config',
            },
        ),
        migrations.AlterModelOptions(
            name='eventconfig',
            options={'verbose_name': 'Single Event Config'},
        ),
        migrations.AlterUniqueTogether(
            name='eventconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='regularevent',
            name='app_config',
            field=aldryn_apphooks_config.fields.AppHookConfigField(help_text='When selecting a value, the form is reloaded to get the updated default', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.regulareventconfig'),
        ),
    ]
