# Generated by Django 3.2.12 on 2022-03-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_auto_20220330_2133"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamConfig",
        ),
    ]
