# Generated by Django 3.2.12 on 2022-03-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220331_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='namespace',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='regularevent',
            name='namespace',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Do not include the year/season in this, as it will beautomatically added from the season above.', max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
