runtime: python39

env_variables:
  FIR_ENV: "prod"

entrypoint: gunicorn firweb.asgi:application -b :$PORT  -k uvicorn.workers.UvicornWorker

automatic_scaling:
  min_instances: 0
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
