runtime: python39
instance_class: F2


inbound_services:
- warmup

automatic_scaling:
  min_instances: 0
  max_concurrent_requests: 20

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301