runtime: python39

env_variables:
  FIR_ENV: "prod"

app_engine_apis: true

inbound_services:
- warmup

automatic_scaling:
  min_instances: 0

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301