runtime: python39
threadsafe: yes

env_variables:
  FIR_ENV: "prod"

automatic_scaling:
  min_instances: 0
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
