on:
  [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: Gr1N/setup-poetry@v7

      - name: Install Python Dependencies
        run: poetry install && poetry shell

      - name: Install Node Dependencies
        run: |
          cd theme
          yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          eslint: true
          eslint_dir: ./theme/ts/
          eslint_extensions: js,ts
          stylelint: true
          stylelint_dir: ./theme/sass/
          auto_fix: true
